version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-vps-bot
    restart: always
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
